### ISSUE TITLE
[ELWGWAR] Galactiwars - Crashes on Initialization

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#127]
**Module Information**
* Identifier: ELWGWAR
* Module Name: Galactiwars
* Version: 4.1

**Describe the bug**
Crashes on Initialization

**To Reproduce**
1. Add to moduleConfig.json
2. Start MBBSEmu

**Expected behavior**
Module Loads

**Screenshots**
```
Critical Exception has occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.stgopt()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
So this one is interesting. The module calls `STGOPT` before opening an MCV of setting the currently active with `SETMBK`. MBBSEmu is throwing an exception because, technically, there isn't an MCV file open to perform the `STGOPT` action on. 

There might be some logic where, during a Module's `_INIT_` routine that the modules MCV file is opened implicitly? Technically this doesn't abide by any documentation I can find. So we'll need to research the actual behavior vs. expected.

**Comment by enusbaum** [comment]
![image](https://user-images.githubusercontent.com/1139047/93514129-d35cbb80-f8f4-11ea-8384-17a6ec2b5e11.png)

**Comment by enusbaum** [comment]
This does appear to be a bug in the Module Galactic Wars. 

```c
void EXPORT init__example(void)
{

	//debugFile=opnmsg("example.mcv");
	//setmbk(debugFile);
	shocst("Reading MCV", "Value: %s", stgopt(1));

	moduleState = register_module(&example);
	
};
```

Returns:
![image](https://user-images.githubusercontent.com/1139047/93517060-ec676b80-f8f8-11ea-9ee5-bdcc15ea5a24.png)

If I un-comment the commented out sections, the value reads properly from the MCV:

```c
void EXPORT init__example(void)
{

	debugFile=opnmsg("example.mcv");
	setmbk(debugFile);
	shocst("Reading MCV", "Value: %s", stgopt(1));

	moduleState = register_module(&example);
	
};
```

![image](https://user-images.githubusercontent.com/1139047/93517251-2fc1da00-f8f9-11ea-8a49-b070977d9ae4.png)

So the fix here is to make MBBSEmu not throw an unhandled exception when trying to perform an MCV operation when one isn't set.  

I'll report the module issue on the forums.

**Comment by tuday2** [comment]
Closing until ISV corrects issue
