### ISSUE TITLE
[ELWWOW] War of Worlds! - Module crashes on initialization

### ISSUE THREAD

**Issue by enusbaum** [enusbaum/MBBSEmu#155]
**Module Information**
* ELWWOW
* War of Worlds!
* 2.0

**Describe the bug**
War of Worlds performs a `getbtvl()` on an empty Btrieve file (`ELWWOWC.EMU`) causing MBBSEmu to crash. 

There is logic in `GetRecordByOffset()` to throw an exception if there is no record found at the current position/offset. This is the error being thrown. Because `getbtvl()` is `void` and doesn't return an error in this case, we need to verify how Btrieve handles this case internally. 

Do we just return a null record?

![image](https://user-images.githubusercontent.com/1139047/94995006-4444da00-0569-11eb-8cb8-4451a29143b3.png)

**Comment by tuday2** [comment]
After further investigation you have to run the world initialization executable "ELWWOWU.EXE" which needs a .MCV file

![Screenshot 2020-11-01 113015](https://user-images.githubusercontent.com/27604078/97809907-b1659100-1c35-11eb-9c01-162232f0b5ba.jpg)

**Comment by tuday2** [comment]
Closing until we can find non-repackaged game
