### ISSUE TITLE
[ELWTAROT] Tarot Card - Missing date text variable, causes malformed screen

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#158]
**Module Information**
* Identifier: ELWTAROT
* Module Name: Tarot Card
* Version: 1.1

**Describe the bug**
Unable to display date, missing text variable

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter module from menu

**Expected behavior**
Show today's date

**Screenshots**
```
2020-10-04 21:37:00.8332 Error MBBSEmu.HostProcess.ExportedModules.ExportedModuleBase.ProcessTextVariables Unknown Text Variable: DATE
```
![Screenshot 2020-10-04 214020](https://user-images.githubusercontent.com/27604078/95035285-3aff5e80-068a-11eb-9caf-f31e2b304862.jpg)

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
There are several "Built In" Text Variables in the system. `DATE` being one of them, as `REGISTER_VAR` is never called by ELWTAROT.

In `ExportedModuleBase.ProcessTextVariables()` there is a switch on the variable name being looked up. We have one of the system variables already defined for `USERID`, we'd just need to add one for date.
