### ISSUE TITLE
Module data doesn't save on Ctrl-C

### ISSUE THREAD

**Issue by paladine** [enusbaum/MBBSEmu#18]
If you exit MBBSEmu via ctrl-c, it doesn't give the loaded modules a chance to save their data. 

We ought to install a [Cancel Key handler](https://docs.microsoft.com/en-us/dotnet/api/system.console.cancelkeypress?redirectedfrom=MSDN&view=netcore-3.1) that calls all the module shutdown routines before finally exiting.

**Comment by enusbaum** [comment]
Addressed with https://github.com/enusbaum/MBBSEmu/pull/21

huprou() and finrou() are now properly invoked

🥇
