### ISSUE TITLE
[MBBSEmu] mbbsemu-win-x32-101120-4 -  Lists loaded modules in reverse order

### ISSUE THREAD

**Issue by BlaZZZed1980** [enusbaum/MBBSEmu#189]
**Module Information**
* MBBSEmu
* mbbsemu-win-x32-101120-4

**Describe the bug**
Loaded modules are listed in reverse order

**To Reproduce**
1. Log into a mbbsemu-win-x32-101120-4 server.

**Expected behavior**
Previous versions listed modules in the correct order.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/71443181/95775148-73ed9380-0c87-11eb-95bb-dad9b84840c3.PNG)

**Software Information:**
- OS: Windows 7 32-bit

**Comment by enusbaum** [comment]
This might have been introduced with #120, as the menu is displayed from the unordered modules list. 

I'll push a quick PR for this that'll word the menu items sorted by their `MenuOptionKey`

**Comment by BlaZZZed1980** [comment]
Just tested with mbbsemu-win-x32-101220-8 and this bug has been fixed.  Awesome!

**Comment by BlaZZZed1980** [comment]
Interestingly, it appears that after cleanup the modules are again in reverse order.  I will run some tests when I get home from work to see if this is indeed when it reverted back.

**Comment by enusbaum** [comment]
Give the latest build from this morning a try 👍 

https://www.mbbsemu.com/Downloads/master/101320

**Comment by BlaZZZed1980** [comment]
Just got this new build installed and things are back to normal.  I'll let you know if there are any issues after cleanup tonight.

**Comment by BlaZZZed1980** [comment]
All good this time.  :)
