### ISSUE TITLE
[WCCMMUD] MajorMud - WHO command shows extra characters "%"

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#205]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
WHO command shows extra characters "%"

**To Reproduce**
1. Enter MajorMud module
2. Create character if none exists, enter game
3. Execute "WHO" command
4. See Error

**Expected behavior**
Show characters online without garbage characters

**Screenshots**
```
No Console Error
```

![MMWHO](https://user-images.githubusercontent.com/27604078/96357114-cc27f980-10bc-11eb-8c10-c9958d8ef440.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101820-1

**Comment by enusbaum** [comment]
Just checked and this is still an issue with the latest `master` build.

This might be an issue with the PLAYER record (`WCCUSERS.DAT`), as it appears to be looping through a Btrieve file and uses data from the player struct to pass that into sprintf.

<img width="984" alt="Screen Shot 2020-10-23 at 3 22 57 PM" src="https://user-images.githubusercontent.com/1139047/97045393-aaf35d00-1543-11eb-8fc5-4f6c4eafa0db.png">

I'll need to debug if there's an issue with either the player record itself or perhaps the offset is incorrect.

**Comment by tuday2** [comment]
Fixed in Build 103120-15
