### ISSUE TITLE
Improve error messages with invalid appsettings.json values

### ISSUE THREAD

**Issue by paladine** [enusbaum/MBBSEmu#209]
Generally the system is intolerant of missing/invalid appsettings.json values. If you're missing `Database.File`, you get some random message about missing the database but no guidance on how to resolve it. 

If missing `GSBL.Activation`, it just crashes with no guidance at all.

Audit all the settings and make sure that the program exits gracefully with useful instructions.

**Comment by tuday2** [comment]
Close Me @enusbaum

**Comment by enusbaum** [comment]
Fixed with #215
