### ISSUE TITLE
[HVSXROAD] CROSSROADS - Alias Input Issue

### ISSUE THREAD

**Issue by cschoppy** [enusbaum/MBBSEmu#216]
**Module Information**
* Identifier [HVSXROAD]
* Module Name [CROSSROADS]

**Describe the bug**
When entering username alias at startup, input is not recognized.

**To Reproduce**
Launch module, attempt to enter a username.

**Expected behavior**
Username/alias accepted - Module continues execution.

**Screenshots**
Please see attached.

**Software Information:**
- OS: Windows Server 2019
- Telnet Client Syncterm and NetRunner

![image](https://user-images.githubusercontent.com/1312575/97119680-2ee64a00-16e8-11eb-9e3b-14a04684706f.png)

**Comment by enusbaum** [comment]
The issue was caused by `CNCALL` returning a bad pointer. I believe this regression was caused by all the fixes we've done around `CNCxxxx` ordinals and `NXTCMD`, which brought this issue to light. It previously just worked by accident 😝
