### ISSUE TITLE
[WCCMMUD] MajorMud - On linux the wccmmud.dll can't find the update file ext4 file system

### ISSUE THREAD

**Issue by bloodrock** [enusbaum/MBBSEmu#24]

**Comment by enusbaum** [comment]
![image](https://user-images.githubusercontent.com/1139047/90528256-6cef4c80-e140-11ea-8045-60ffc6f75e6d.png)

**Comment by dlightman311** [comment]
I have verified this does not occur when majormud is hosted on a case insensitive file system and may have a relationship to the SoC issue.

**Comment by paladine** [comment]
I need some more information, what's the full path of your `WCCUPDAT.DAT` file?

**Comment by tuday2** [comment]
@bloodrock Can you verify if this is still occuring?

**Comment by tuday2** [comment]
Please re-open if still an issue but the latest build should work on most flavors of Linux.
