### ISSUE TITLE
[MBBSEmu] Telnet Server - Telnet Heartbeat ( 0xFF, 0xF1 ) is conflicting with MegaMUD

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#248]
**Module Information**
* Identifier: MBBSEmu
* Version: 110120-4

**Describe the bug**
Telnet Heartbeat ( 0xFF, 0xF1 ) is conflicting with MegaMUD

**To Reproduce**
1. Load Majormud in MBBSEmu
2. Connect with Megamud telnet client
3. See error

**Expected behavior**
Megamud does not give errors

**Screenshots**
Code from Telnet Server
```
private static readonly byte[] IAC_NOP = { 0xFF, 0xF1};
```
![Megamud](https://user-images.githubusercontent.com/27604078/97825011-172c3a00-1c83-11eb-84c1-9646f173db8e.png)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: MegaMUD
- MBBSEmu Build: 110120-4

**Comment by paladine** [comment]
Adding this as a configuration option would be cool.
