### ISSUE TITLE
[HVSXROAD] Crossroads of the Elements - Sysop access to all users

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#249]
**Module Information**
* Identifier [HVSXROAD]
* Module Name [Crossroads of the Elements]
* Version [1.00j]

**Describe the bug**
All users have sysop level access in the game "sys" commands. E.g., SYS GOTO, SYS UPDATE, SYS BECOME, etc...

**To Reproduce**
1. Create new user account
2. Load Crossroads
3. Issue the "sys" command

**Expected behavior**
Only users with "sysop" keys or role should have the ability to run sysop commands.

**Screenshots**
N/A

**Software Information:**
- OS: [Fedora 32 and CentOS 8]
- Telnet Client [Linux telnet, Telix under DOSBox]

**Comment by enusbaum** [comment]
Currently both `haskey()` and `hasmkey()` Ordinals return `true` for every key, regardless if the user has it. 

I'm working on a Branch right now which sets default keys for new users and properly evaluates the keys assigned to a user. 

PR pending.

**Comment by brianmiller** [comment]
Excellent.  As soon as this is implemented, I'm ready to replace by BBS. :)

I'm happy to test.
