### ISSUE TITLE
[HVSXROAD] Crossroads of the Elements - Reg key / level limitation

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#252]
**Module Information**
* Identifier [HVSXROAD]
* Module Name [Crossroads of the Elements]
* Version [1.00j]

**Describe the bug**
Crossroads won't allow more than 5 levels for a player.  I recall this being related to an unregistered game.  

I have my own MBBS625 and HVSXROAD married keys if MBBSEmu can accept them, or are we expecting to eliminate reg keys--I'm not sure if that is an option.

**To Reproduce**
1. Start Crossroads
2. Issue the command "sys spe 29" to add levels
3. Issue the command "stats" to view current level
4. Observe a total of 5 levels (1 PHY / 4 SPE)

**Expected behavior**
All levels added. In the +29 levels as described above, we should see 1 PHY and 30 SPE levels. A total of 31 levels is expected.

**Screenshots**
N/A

**Software Information:**
- OS: [Fedora 32 and CentOS 8]
- Telnet Client [Linux telnet, Telix in DOSBox]

**Comment by enusbaum** [comment]
You're able to pair your registered copies of modules with MBBSEmu by setting your MBBS Reg. Number through the `appconfig.json` ([Link](https://github.com/enusbaum/MBBSEmu/wiki/appsettings.json-Configuration-File)), and then also setting your Crossroads Activation Code in the proper MSG file value.

If you had multiple boards/reg numbers, you're also able to set MBBS Reg. Numbers that each module will see. Details are in the Wiki as well.

**Comment by brianmiller** [comment]
Thank you for the info and apologies for missing the wiki.  I applied my codes and can see the following in the startup log:

2020-11-04 08:53:28.9267 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl..ctor Found Module Specific Activation # for HVSXROAD. Setting BTURNO to: *******

I'm using the same codes I've used for decades which works with the native DOS software but they're not working with MBBSemu.  Crossroads still won't go past 5 levels.  I'll play with it a bit more.

**Comment by enusbaum** [comment]
Thanks for debugging that for us! We'll take a look at the registration routine for HVSXROAD and see if there's an emulation issue calculating a correct registration code. 👍

**Comment by brianmiller** [comment]
> Thanks for debugging that for us! We'll take a look at the registration routine for HVSXROAD and see if there's an emulation issue calculating a correct registration code.

No problem and thank you for the incredible work.  I'm loving it.

**Comment by brianmiller** [comment]
It was my fault and I don't want you to waste your time on my nonsense. 

The wiki didn't describe the module activation code needs to be set within the modules .MSG file itself (or I completely missed it), but you did mention it in this issue thread.

Towards the top of the HVSXROAD.MSG file: 

**`ACTCODE {12345678} S 8 Crossroads activation code`**

Once I set this and set "GSBL.Activation" in appsettings.json, the game is working as expected.

I suspect every module actcode directives will need unique "guides" to help people out. :)

**Comment by enusbaum** [comment]
Happy to hear you got it working! 

Yeah -- our plan is to hopefully build out the project Wiki with a distinct page for each module to talk about any "gotchas" needed to make it work within the system. I think the MSG value are going to be the current pain if only because there's not a UI in MBBSEmu to set them (yet 😉)

Thanks again for the testing! I'll go ahead and close this issue for now. Feel free to open any new issues if you run across any new ones 👍
