### ISSUE TITLE
[MBBSEmu] MBBS Emulator - Multiple logins from the same user allowed

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#253]
**Module Information**
* Identifier [MBBSEmu (found when testing HVSXROAD)]
* Module Name [MBBSEmu]
* Version [110220-2]

**Describe the bug**
Multiple concurrent logins allows (tested with Sysop).  I found this issue when testing Crossroads.  Two active sysop logins and both were able to join the game.  

**To Reproduce**
1. Login more than once at the same time with the same user

**Expected behavior**
Only one active login should be allowed.  MBBS and WG will let you know during logon that the user is already logged in and boots the previous user.

**Screenshots**
![Screenshot from 2020-11-04 19-22-28](https://user-images.githubusercontent.com/342276/98193955-2bff0c80-1ed3-11eb-8d45-2fca39ef1aa8.png)
]

Screen shots of expected vs. actual between MBBSEmu and MajorBBS/Worldgroup help with understanding the expected difference between the two.

**Software Information:**
- OS: [Fedora 32 and CentOS 8]
- Telnet Client [Linux telnet and Telix via DOSBox

**Comment by enusbaum** [comment]
We have a PR open to address this (#251) which should be merged in within the next day or so 👍

**Comment by brianmiller** [comment]
> We have a PR open to address this (#251) which should be merged in within the next day or so

Fantastic!
