### ISSUE TITLE
[MBBSEmu] MBBSEmu - Usernames are case sensitive 

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#271]
**Module Information**
* Identifier [MBBSEmu]
* Module Name [MBBSEmu]
* Version [#110620-18]

**Describe the bug**
Usernames appear to be case sensitive. The original MBBS and WG systems would not allow two identical names, even with differences in case.  E.g. username "test" and "Test" should be the same user.

**To Reproduce**
1. Create a user, e.g., "test"
2. Create a user. e.g., "Test"
3. Observe how these are two different users
 
**Expected behavior**
Username validation should not be case sensitive.

**Software Information:**
- OS: [Fedora 32 and CentOS 8]
- Telnet Client [Linux telnet and Telix via DOSBox]

**Comment by enusbaum** [comment]
I'll need to add `COLLATE NOCASE` to the SQLite queries against the Username column in `Accounts`. I'll get this added!

**Comment by brianmiller** [comment]
Incredible commitment and willingness to collaborate. Thank you. I'm loving it enjoy testing the software. 

I'm looking forward to getting my systems converted.

**Comment by tuday2** [comment]
Is your BBS public ? Would love to check it out once the conversion is complete
