### ISSUE TITLE
[HVSXROAD] Crossroads of the Elements - Usernames are case sensitive in modules

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#280]
**Module Information**
* Identifier [HVSXROAD]
* Module Name [Crossroads of the Elements]
* Version [1.00j]

**Describe the bug**
Issue #271 and #274 fixed the case sensitivity problem for MBBSEmu's global identity and works perfectly.  Modules (i've only tested HVSXROAD so far) are still case sensitive.  E.g., User "Tester" and "tester" are the same now for MBBSEmu but if the user "Tester" started Crossroads then logged into MBBSEmu as "tester", Crossroads doesn't recognize the user and asks to create a new game identity.

I've added screenshots to better depict the problem.

**To Reproduce**
1. Create a MBSSEmu user "Tester"
2. Start Crossroads and create a game user
3. Logout
4. Login as "tester"
4. Start Crossroads and observe

**Expected behavior**
All modules should be case insensitive, just as the global system now is.

**Screenshots**
Logged in as "Tester"
![Screenshot from 2020-11-09 10-41-54](https://user-images.githubusercontent.com/342276/98582800-4c82ea00-2278-11eb-8793-fa3164575e2a.png)

Logged in as "tester"
![Screenshot from 2020-11-09 10-42-32](https://user-images.githubusercontent.com/342276/98582802-4d1b8080-2278-11eb-9f87-7bb7bdd37c58.png)

**Software Information:**
- OS: [Fedora 32]
- Telnet Client [Telix via DOSBox]

**Comment by paladine** [comment]
After the user is verified, the username in the `Session` should be overwritten with the value in the database, not what the user has entered

**Comment by brianmiller** [comment]
> After the user is verified, the username in the `Session` should be overwritten with the value in the database, not what the user has entered

Is this something that is already in place and not working or something that needs to be implemented?

**Comment by paladine** [comment]
It needs to be implemented. I was just commenting on the work that must be done on our end.

**Comment by brianmiller** [comment]
> It needs to be implemented. I was just commenting on the work that must be done on our end.

Understood.  Thank you :)
