### ISSUE TITLE
[HVSXROAD] Crossroads of the Elements - High score board won't populate after cleanup

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#286]
**Module Information**
* Identifier [HVSXROAD]
* Module Name [Crossroads of the Elements]
* Version [1.00j]

**Describe the bug**
I've added a few screenshots to show the issue.  The high score board stays blank, even after players reach above level 1/1.

**To Reproduce**
1. Start Crossroads (as a NORMAL user)
2. Level up
3. Wait until cleanup
4. Observe the score board

**Expected behavior**
The score board is populated with non-sysop users that are above level 1/1.

**Screenshots**
**You can see the nightly cleanup event and reference the work being done with HVSXROAD**
![Screenshot from 2020-11-12 06-32-15](https://user-images.githubusercontent.com/342276/98952888-d4ebcf80-24b0-11eb-84c5-62e4c62df086.png)

**This is what the high score board looks like if no users in the system qualify to be on the board. E.g., not greater than level 1/1, or a sysop.**
![Screenshot from 2020-11-12 06-31-42](https://user-images.githubusercontent.com/342276/98952950-e9c86300-24b0-11eb-8df4-c21505eb8400.png)

**Here is a player that is level 1/30. You can see the scoreboard after the cleanup changed.  The "<None!>" descriptors are gone, indicating the system knows a user qualifies, but simply isn't being populated.**
![Screenshot from 2020-11-12 06-30-08](https://user-images.githubusercontent.com/342276/98953053-0bc1e580-24b1-11eb-8ff8-8f9151a9ae79.png)

**Software Information:**
- OS: [Fedora 32]
- Telnet Client [Linux telnet and Telix via DOSBox]

**Comment by brianmiller** [comment]
I did a bit more testing to see if I can get anything to appear on the score board.  Collecting all talismans and bringing them to Town Square makes you the "Master of the Elements".  This works and the game does update the score board.

![Screenshot from 2020-11-12 11-22-32](https://user-images.githubusercontent.com/342276/98986174-67a06480-24d9-11eb-9236-4186afc2f45a.png)

![Screenshot from 2020-11-12 11-22-46](https://user-images.githubusercontent.com/342276/98986175-6838fb00-24d9-11eb-9355-adb8365bd985.png)

**Comment by enusbaum** [comment]
Thanks for debugging this! I'll take a look at the disassmebly to see if I can noodle out what's going on.

**Comment by paladine** [comment]
I debugged a bit and discovered this data comes from a file called `HVSXSCOR.XDA`
Each entry in the file is a single line of text. I edited the file to have the following contents
```
Test1
Test2
Test3
Test4
Test5
Test1
Test2
Test3
Test4
Test5
Test1
Test2
Test3
Test4
Test5
Test1
Test2
Test3
Test4
Test5
Test1
Test2
Test3
Test4
Test5
```

And it resulted in the following display:

```
             Current Master of the Elements: Queyan                                                                      
                                                                                                                         
  Element     First      Second     Third      Fourth     Fifth                                                          
  -------     ---------- ---------- ---------- ---------- ----------                                                     
  Earth       Test1      Test2      Test3      Test4      Test5                                                          
  Air         Test1      Test2      Test3      Test4      Test5                                                          
  Fire        Test1      Test2      Test3      Test4      Test5                                                          
  Water       Test1      Test2      Test3      Test4      Test5                                                          
                                                                                                                         
  Top spellcaster: Test1                                                                                                 
                                                                                                                         
  Top fighter: Test2                                                                                                     
                                                                                                                         
Your command? (P/I/H/X):                                                               
```

So if the display works properly, we can assume that the calculation/creation of this file at cleanup time doesn't work properly.

**Comment by enusbaum** [comment]
Tracing through it, there's a function that's called from `_INIT_XROADS` which creates a new `HVSXCOR.XDA` which values of `<None>\0`. I've verified this function works properly and writes the file as intended. 

Looking into what runs during cleanup.

**Comment by paladine** [comment]
I decompiled with MBBSDASM and found the section that wrote the file, and it called `0006.1C2E` a bunch before calling `fprintf`. I can only assume this subroutine computed what was necessary, but the decompile didn't have instructions decompiled at that instruction, so I couldn't investigate further. Maybe IDA will have better luck

```
00016C26h:0006.1C26h 44              inc sp                        ; /---- BEGIN SUBROUTINE 39
00016C27h:0006.1C27h 1B571B          sbb dx, [bx+0x1b]
00016C2Ah:0006.1C2Ah 6B1B7F          imul bx, [bp+di], 0x7f
00016C2Dh:0006.1C2Dh 1B558B          sbb dx, [di-0x75]
00016C30h:0006.1C30h EC              in al, dx
00016C31h:0006.1C31h 56              push si
00016C32h:0006.1C32h 1E              push ds
00016C33h:0006.1C33h B8FFFF          mov ax, 0xffff                ; SEG ADDR of Segment 14
00016C36h:0006.1C36h 8ED8            mov ds, ax
00016C38h:0006.1C38h 33F6            xor si, si
00016C3Ah:0006.1C3Ah 8BC6            mov ax, si                    ; Conditional jump from 0006:1C5Eh
00016C3Ch:0006.1C3Ch 6BC00E          imul ax, ax, 0xe
00016C3Fh:0006.1C3Fh 8B560A          mov dx, [bp+0xa]
00016C42h:0006.1C42h 03D0            add dx, ax
```

**Comment by paladine** [comment]
BTW it called `0006.1C2E` four times consecutively, so I'm assuming it calls it once per element which makes sense

**Comment by enusbaum** [comment]
Here's the query it's running to get the high scores in XROAD's, still stepping through it. 

<img width="769" alt="Screen Shot 2020-11-13 at 12 38 50 PM" src="https://user-images.githubusercontent.com/1139047/99103271-558ff600-25ad-11eb-8815-dd219268272d.png">

**Comment by brianmiller** [comment]
It's incredible to see the motivation and your abilities. This is crack to me.

**Comment by enusbaum** [comment]
I suspect this might be a key related issue. The ordinal `uidkey()` was still returning `TRUE` regardless of the username & key that was passed in. I've pushed a new branch that addresses this. 

When I tested locally it still didn't create the file properly, but it might be my players not being included for whatever reason. We're testing further.

**Comment by brianmiller** [comment]
I'll test out the new build as well.

**Comment by enusbaum** [comment]
We were able to identify the issue. It was a combination of two defects. 

First was the above mentioned issue with `uidkey()`

The second issue was in `F_PRINTF()` which prints a string to a file pointer. The issue is it was printing the entire string, null included. These null terminators should not have been written to the output stream and were messing up the file logic. Fixing both of these issues allowed both the top players of Crossroads to be written to `HVSXSCOR.XDA`

PR pending once I complete writing the Unit Tests 👍

**Comment by brianmiller** [comment]
Fantastic!!

**Comment by brianmiller** [comment]
Thank you for fixing this. It looks like it's working as expected now.

![Screenshot from 2020-11-14 08-56-11](https://user-images.githubusercontent.com/342276/99152552-4e252700-2657-11eb-9f1c-b0f6f98ea8a5.png)
