### ISSUE TITLE
[CORE] Investigate ways to reduce CPU usage

### ISSUE THREAD

**Issue by paladine** [enusbaum/MBBSEmu#318]
Investigate how we can remove the `while (true) { do_bbs_work(); }` with something more event driven, so that we don't chew up 100% of the CPU.

Initial thoughts are:

- Perform work on a timer that runs at a certain user configurable interval, such as 100hz. Lower number uses less CPU, higher number provides more responsiveness
- Suspend background activities entirely when no clients are connected, allowing the system to go down to 0% CPU. Might cause some issues with games like Tele-Arena that use the timers to respawn enemies.

**Comment by tuday2** [comment]
Closed by #353
