### ISSUE TITLE
[GWWARROW] Archery - Freezes at menu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#357]
**Module Information**
* Identifier: GWWARROW
* Module Name: Archery
* Version: 1.4D

**Describe the bug**
Freezes at menu

**To Reproduce**
1. Add module to config
2. Load MBBSEmu
3. See error

**Expected behavior**
Arrow plays normally

**Screenshots**
![image](https://user-images.githubusercontent.com/27604078/103308763-d2015b80-49d8-11eb-89fe-b8e62e334107.png)

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by TQPS** [comment]
This was working fine a couple of days ago (28th last successful run).

**Comment by tuday2** [comment]
Closed with PR #360
