### ISSUE TITLE
Telnet text entry echo'd twice, \n not interpreted by MBBSEmu

### ISSUE THREAD

**Issue by ryanfantus** [enusbaum/MBBSEmu#36]
In the 081920-8 build (and a previous one that I don't recall) I can't get MBBSEmu to do anything with the text I enter while using console telnet. When I type my username, it just echos back what I typed, and I can't get it to do anything else. I have to manually ctrl-c to break out of it.

![image](https://user-images.githubusercontent.com/1007329/90810186-70690c00-e2d7-11ea-8e76-9009580780bf.png)

**Comment by ryanfantus** [comment]
Also, this is linux, 64 bit, Ubuntu 20.04 if it matters.

**Comment by enusbaum** [comment]
Confirmed for Linux command line telnet, if you're running MBBSEmu on a non-standard port (!= 23), Linux telnet will not negotiate IAC resulting in some weirdness. 

To fix this run telnet via: 

`telnet -- <host>-<port>`
