### ISSUE TITLE
(DIALCHAT) DialChat - Demo expires after cleanup

### ISSUE THREAD

**Issue by dlightman311** [enusbaum/MBBSEmu#45]
After nightly cleanup runs DialChat blocks entry with a message that the 5 day demo period has expired even though it has ran for less than 24 hours.

**Comment by enusbaum** [comment]
I suspect this might have been related to the Btrieve Segmented Key issue which impacted `GENBB` and it pulling in the incorrect record using `OBTBTV` fixed in PR #106 

Please re-test and report back 👍

**Comment by BlaZZZed1980** [comment]
I can confirm this is still an active bug, though I'm not sure cleanup is when it happens.  Sometimes just taking the server down and bringing it back up will cause this to occur.

**Comment by BlaZZZed1980** [comment]
My cleanup ran successfully last night at 3am and did not expire the DialChat Demo.  Whenever it does expire, I have to delete all the auto-generated files out of the MBBSEmu directory and allow them to re-create at the next startup.  Then DialChat will work again.  I can't yet figure out exactly when this is happening.

**Comment by enusbaum** [comment]
Thanks @BlaZZZed1980 for confirming that cleanup didn't expire. The Demo install date is probably saved in BBSGEN.DAT, which is the generic Btrieve Database. I should probably write some kind of editor for folks to easily modify that information.
