### ISSUE TITLE
[SFAYTZ] Yahtzee - No Instructions displayed when you type "I" from the Main Menu

### ISSUE THREAD

**Issue by enusbaum** [enusbaum/MBBSEmu#66]
**Module Information**
* SFAYTZ
* Yahtzee

**Describe the bug**
When trying to display instructions, nothing is displayed and it hangs until you hit enter.

**To Reproduce**
1. Enter the Module
2. Hit I
3. Observe blank output
4. Hit enter to return to main menu

**Expected behavior**
Instructions should appear

** Technical Information **

It appears SFAYTZ does an open of `SFAYTZ.INS` and should output the content but it is not. The loop is the module going into deferred execution by calling `btuinj` for status 240. This is how it monitors for "Enter" before re-displaying the menu.

It opens the file successfully and saves the pointer, but it's not displaying the contents.

**Comment by tuday2** [comment]
Fixed - confirmed in Build 100720-7

@enusbaum please close
