### ISSUE TITLE
[MBBSEmu] RLogin - First entry is ignored upon connection

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#70]
**Module Information**
* Identifier: MBBSEmu
* Module Name: Rlogin
* Version: 08-29-2020-1 

**Describe the bug**
Upon connecting to the "menu" based RLogin port from MysticBBS I am shown the menu of modules, no matter what I enter it ignores and shows the menu again. Once the menu is repeated you can now select a module and everything works.

**To Reproduce**
1. Connect to RLogin menu port (shows list of modules)
2. Enter any number 1-9, the menu will repeat itself as if you didn't pick anything

**Expected behavior**
Initial menu will allow you to enter a module

**Screenshots**
![Annotation 2020-08-29 104103](https://user-images.githubusercontent.com/27604078/91642416-d731a800-e9f0-11ea-80c3-0384094ca2ac.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
I suspect there might be data left in the input buffer after rlogin, so while you're entering `1`, the input processor is receiving `<data>1`, and since that's an invalid menu option, it's re-displaying the menu.

**Comment by enusbaum** [comment]
Closed -- verified fixed in #76
