### ISSUE TITLE
[WCCMMUD] MajorMud - Loading .DAT file with Btrieve

### ISSUE THREAD

**Issue by lucid2310** [enusbaum/MBBSEmu#9]
There is an issue when loading the WCCTEXT.DAT file, it cannot find the textblock records.

**Comment by lucid2310** [comment]
@enusbaum I couldn't add labels or assign, if you can add Majormud label and assign it to me, I am investigating the issue.

**Comment by enusbaum** [comment]
@lucid2310 If you can set a break point after the records are loaded from the .DAT file and use the WriteRecoveryFile() method to dump the records similar to how "BUTIL -RECOVER" would. This should allow you to trouble shoot if there's an offset issue with the records. 

https://github.com/enusbaum/MBBSEmu/blob/master/MBBSEmu/Btrieve/BtrieveFileProcessor.cs#L1091

**Comment by enusbaum** [comment]
@lucid2310 This might be fixed in #14 as WCCTEXT.DAT used a numeric key, if it was performing a `GetKeyNext()` and getting zero on the first record.

![image](https://user-images.githubusercontent.com/1139047/90182631-43b96f80-dd80-11ea-8f70-88a3da9cd7a3.png)

**Comment by lucid2310** [comment]
I will check it when I get home, thanks for taking a look at this as well.

**Comment by tuday2** [comment]
@paladine This is fixed now right?

**Comment by tuday2** [comment]
Fixed in #268
